name: greate a user

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Gree the user
        run: |
          echo "Hello, $(git log -1 --pretty=format:'%an')!"
          echo "Thanks for pushing to the main branch"
